name: service_settings
description: This package contains an API to manipulate Eike-Settings
publish_to: none
version: 0.0.1 # Literally does not matter
resolution: workspace

environment:
  sdk: ^3.13.2

dependencies:
  meta:
  use_in_case:
  rx_shared_preferences:
  service_logging:

dev_dependencies:
  test:
