name: eike_workspace
description: A workspace for the eike frontend application.
publish_to: none
version: 0.8.2

environment:
  sdk: ^3.12.2
  flutter: ^3.44.2

workspace:
  - packages/data_database
  - packages/data_entities

  - packages/eike_app

  - packages/feat_app_protection
  - packages/feat_contact
  - packages/feat_database_provider
  - packages/feat_home
  - packages/feat_imprint
  - packages/feat_licenses
  - packages/feat_navigation
  - packages/feat_privacy_policy
  - packages/feat_settings
  - packages/feat_notification

  - packages/service_auth
  - packages/service_design
  - packages/service_logging
  - packages/service_settings
  - packages/service_url_launcher

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.0.0
  drift: ^2.34.0
  sqlite3: ^3.3.3
  sqlcipher_flutter_libs: ^0.7.0+eol
  flutter_secure_storage: ^10.0.0
  path: ^1.9.0
  path_provider: ^2.1.6
  provider: ^6.1.5+1
  local_auth: ^3.0.1
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  flutter_svg: ^2.2.3
  freezed_annotation: ^3.1.0
  flutter_bloc: ^9.1.1
  bloc_presentation: ^1.1.2
  bloc_concurrency: ^0.3.0
  json_annotation: ^4.11.0
  use_in_case: ^1.4.3
  dartz: ^0.10.1
  logger: ^2.6.2
  rx_shared_preferences: ^4.0.0
  meta: ^1.18.0
  flex_color_scheme: ^8.4.0
  google_fonts: ^8.0.2
  flutter_html: ^3.0.0
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  http: ^1.2.0
  drift_dev: ^2.34.0
  build_runner: ^2.4.0
  flutter_launcher_icons: ^0.14.4
  freezed: ^4.0.0
  json_serializable: ^6.13.0
  test: ^1.31.0
