name: eike_app
description: "Die EIKE-App bietet Einsatzkräften Informationen und Unterstützung bei der Vorbereitung und Verarbeitung von belastenden Einsätzen."
publish_to: none
version: 0.8.7

environment:
  sdk: ^3.13.2
  flutter: ^3.47.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^18.0.0
  drift: ^2.34.0
  sqlite3: ^3.3.3
  sqlcipher_flutter_libs: ^0.7.0+eol
  encrypted_drift:
    git:
      url: https://github.com/simolus3/drift.git
      path: extras/encryption
  flutter_secure_storage: ^11.0.0
  path: ^1.9.0
  path_provider: ^2.1.6
  provider: ^6.1.5+1
  local_auth: ^3.0.1
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  flutter_svg: ^2.2.3
  freezed_annotation: ^3.1.0
  flutter_bloc: ^9.1.1
  bloc_presentation: ^1.1.2
  bloc_concurrency: ^0.3.0
  json_annotation: ^4.11.0
  use_in_case: ^1.4.3
  dartz: ^0.10.1
  logger: ^2.6.2
  rx_shared_preferences: ^4.0.0
  rxdart: ^0.28.0
  meta: ^1.18.0
  flutter_html: ^3.0.0
  yaml: ^3.1.3
  flutter_native_splash: ^2.4.8
  flutter_animate: ^4.5.2
  package_info_plus: ^10.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  http: ^1.2.0
  archive:
  bloc_test: ^10.0.0
  drift_dev: ^2.34.0
  build_runner: ^2.4.0
  flutter_launcher_icons: ^0.14.4
  freezed: ^4.0.0
  json_serializable: ^6.13.0
  test: ^1.31.0

flutter:
  uses-material-design: true

  assets:
    - assets/content/
    - assets/content/7-things/
    - assets/fonts/Roboto/OFL.txt
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/Roboto/Roboto-Italic-VariableFont_wdth,wght.ttf
          style: italic
