name: data_database
description: The database instance used by eike
publish_to: none
version: 0.0.1 # Literally does not matter
resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ^3.41.2

dependencies:
  flutter:
    sdk: flutter
  drift:

  data_entities:

dev_dependencies:
  build_runner:
  drift_dev:
