name: service_design
description: Provides several components & design specifications for Eike
publish_to: none
version: 0.0.1 # Literally does not matter
resolution: workspace

environment:
  sdk: ^3.13.2
  flutter: ^3.47.2

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme:
  google_fonts:
