name: feat_settings
description: This package contains contents related to the settings screen.
publish_to: none
version: 0.0.1 # Literally does not matter
resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ^3.41.2

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation:
  flutter_bloc:
  bloc_concurrency:
  use_in_case:
  dartz:
  rxdart:
  drift:
  meta:

  data_database:
  data_entities:
  feat_navigation:
  service_design:
  service_logging:
  service_settings:

dev_dependencies:
  test:
  build_runner:
  freezed:
  drift_dev:
  rx_shared_preferences:
