name: feat_app_protection
description: Protection layer that
publish_to: none
version: 0.0.1 # Literally does not matter
resolution: workspace

environment:
  sdk: ^3.11.0
  flutter: ^3.41.2

dependencies:
  flutter:
    sdk: flutter
  drift:
  flutter_bloc:
  freezed_annotation:
  rx_shared_preferences:
  use_in_case:
  dartz:
  service_logging:
  service_settings:
  service_auth:

dev_dependencies:
  test:
  build_runner:
  freezed:
  drift_dev:
