name: service_logging
description: Logging API for the Eike App
publish_to: none
version: 0.0.1 # Literally does not matter
resolution: workspace

environment:
  sdk: ^3.11.0

dependencies:
  logger:
  use_in_case:
