name: service_url_launcher
description: This package abstracts url_launcher into a testable suite
publish_to: none
version: 0.0.1 # Literally does not matter
resolution: workspace

environment:
  sdk: ^3.13.2
  flutter: ^3.47.2

dependencies:
  flutter:
    sdk: flutter
  url_launcher:
  use_in_case:
  flutter_bloc:
  freezed_annotation:

  feat_notification:
  service_bloc:
  service_logging:

dev_dependencies:
  freezed:
  build_runner:
