name: tools_fetch_content
description: This package is a utility
publish_to: none
version: 0.0.1 # Literally does not matter

environment:
  sdk: ^3.11.0

dependencies:
  archive: ^4.0.9
  http: ^1.6.0
  path: ^1.9.1
  yaml: ^3.1.3
